print("Output:")
print(True)
print(not False)
print(1 > 0)
print(not ('a'=='b'))
print(1 > 0 or not ('a'=='b'))
print(5.6 > 2.0 and len('hola') < 2)
print(5.6 > 2.0 or len('hola') < 2)
print(int('3') - 1 == len('x' * 2))
print("------------------------------------------------------")
print("Tipos:")
print(type(True))
print(type(not False))
print(type(1 > 0))
print(type(not ('a'=='b')))
print(type(1 > 0 or not ('a'=='b')))
print(type(5.6 > 2.0 and len('hola') < 2))
print(type(5.6 > 2.0 or len('hola') < 2))
print(type(int('3') - 1 == len('x' * 2)))